language: php
php:
        - 7.2

sudo: false
services: mysql

install:
        - composer install --prefer-dist --no-progress --no-suggest --ansi

script:
        # First, look for PHP standard errors
        - ChANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}")
        - if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php_cs(\\.dist)?|composer\\.lock)$"; then EXTRA_ARGS=$(printf -- '--path-mode=intersection\n--\n%s' "${CHANGED_FILES}"); else EXTRA_ARGS=''; fi
        - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no src
