name: PHP Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Check CS
      run: php vendor/bin/php-cs-fixer fix --diff --config=.php_cs.dist -v --dry-run --using-cache=no src tests
